# Generated by Django 2.2 on 2020-09-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetails',
            name='uploaded',
            field=models.CharField(default=1, max_length=50, verbose_name='Time Uploaded'),
            preserve_default=False,
        ),
    ]
