# Generated by Django 2.2 on 2020-09-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newsdetails_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetails',
            name='author',
            field=models.CharField(default=1, max_length=150, verbose_name='Author Name'),
            preserve_default=False,
        ),
    ]
