# Generated by Django 2.2 on 2020-09-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_newscomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscomment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelTable(
            name='newscomment',
            table=None,
        ),
    ]
